name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "covidcareapp" # Must be unique in Heroku
          heroku_email: "akshay10.thite@gmail.com"
          appdir: "api"
        env:
          HD_MONGODB_URI: ${{secrets.MONGODB_URI}}
          # HD_PORT: ${{secrets.PORT}}
          # HD_SECRET: ${{secrets.SECRET}}